import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from data_loader import load_data

def plot_data(df, ticker):
    """
    Plots the closing price of the stock.
    """
    plt.figure(figsize=(12, 6))
    plt.plot(df['Close'], label=f'{ticker} Close Price')
    plt.title(f'{ticker} Stock Price History')
    plt.xlabel('Date')
    plt.ylabel('Price (USD)')
    plt.legend()
    plt.grid(True)
    print("Close the plot window to continue...")
    plt.show()

def add_technical_indicators(df):
    """
    Adds Technical Indicators to the DataFrame.
    - RSI (Relative Strength Index)
    - EMA (Exponential Moving Average)
    """
    # Calculate RSI
    delta = df['Close'].diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
    rs = gain / loss
    df['RSI'] = 100 - (100 / (1 + rs))
    
    # Calculate EMA (50 days)
    df['EMA_50'] = df['Close'].ewm(span=50, adjust=False).mean()
    
    # Drop NaN values generated by indicators
    df.dropna(inplace=True)
    return df

def scale_data(df):
    """
    Scales the data (Close, RSI, EMA) to be between 0 and 1.
    Returns:
        scaler: The scaler for the entire dataset (features)
        target_scaler: The scaler specifically for the 'Close' price (target)
        scaled_data: The scaled numpy array
    """
    # Ensure indicators are present
    if 'RSI' not in df.columns:
        df = add_technical_indicators(df)
        
    # Features: Close, RSI, EMA_50
    # Note: 'Close' is at index 0
    features = df[['Close', 'RSI', 'EMA_50']].values
    
    # Scale all features
    scaler = MinMaxScaler(feature_range=(0, 1))
    scaled_data = scaler.fit_transform(features)
    
    # Create a separate scaler just for Close price to make inverse_transform easy later
    target_scaler = MinMaxScaler(feature_range=(0, 1))
    target_scaler.fit(df[['Close']].values)
    
    return scaler, target_scaler, scaled_data

if __name__ == "__main__":
    ticker = "AAPL"
    df = load_data(ticker)
    
    if not df.empty:
        # 1. Visualize
        print("Plotting data...")
        plot_data(df, ticker)
        
        # 2. Scale
        print("Scaling data...")
        # 2. Scale
        print("Scaling data...")
        scaler, target_scaler, scaled_data = scale_data(df)
        
        print("\nData Scaled successfully!")
        print(f"Original Close (First row): {df['Close'].iloc[0]}")
        print(f"Scaled Features (First row): {scaled_data[0]}")
